# Generated by Django 5.0.6 on 2024-06-29 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_day', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30)])),
                ('s_month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('s_year', models.IntegerField(choices=[(1408, 1408), (1409, 1409), (1410, 1410), (1411, 1411), (1412, 1412), (1413, 1413), (1414, 1414), (1415, 1415), (1416, 1416), (1417, 1417), (1418, 1418), (1419, 1419), (1420, 1420), (1421, 1421), (1422, 1422), (1423, 1423), (1424, 1424), (1425, 1425), (1426, 1426), (1427, 1427), (1428, 1428), (1429, 1429), (1430, 1430), (1431, 1431), (1432, 1432), (1433, 1433), (1434, 1434), (1435, 1435), (1436, 1436), (1437, 1437), (1438, 1438), (1439, 1439), (1440, 1440), (1441, 1441), (1442, 1442), (1443, 1443), (1444, 1444), (1445, 1445), (1446, 1446), (1447, 1447), (1448, 1448), (1449, 1449), (1400, 1400), (1401, 1401), (1402, 1402), (1403, 1403), (1404, 1404), (1405, 1405), (1406, 1406), (1407, 1407)])),
                ('e_day', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30)])),
                ('e_month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('e_year', models.IntegerField(choices=[(1408, 1408), (1409, 1409), (1410, 1410), (1411, 1411), (1412, 1412), (1413, 1413), (1414, 1414), (1415, 1415), (1416, 1416), (1417, 1417), (1418, 1418), (1419, 1419), (1420, 1420), (1421, 1421), (1422, 1422), (1423, 1423), (1424, 1424), (1425, 1425), (1426, 1426), (1427, 1427), (1428, 1428), (1429, 1429), (1430, 1430), (1431, 1431), (1432, 1432), (1433, 1433), (1434, 1434), (1435, 1435), (1436, 1436), (1437, 1437), (1438, 1438), (1439, 1439), (1440, 1440), (1441, 1441), (1442, 1442), (1443, 1443), (1444, 1444), (1445, 1445), (1446, 1446), (1447, 1447), (1448, 1448), (1449, 1449), (1400, 1400), (1401, 1401), (1402, 1402), (1403, 1403), (1404, 1404), (1405, 1405), (1406, 1406), (1407, 1407)])),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('persons', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('typework', models.CharField(choices=[('گرم', 'گرم'), ('قاشق غذا خوری', 'قاشق غذا خوری'), ('کیلوگرم', 'کیلوگرم'), ('لیتر', 'لیتر')], max_length=100)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='reqq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.material')),
            ],
        ),
        migrations.CreateModel(
            name='foodreqq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.food')),
                ('reqq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.reqq')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='reqqs',
            field=models.ManyToManyField(through='food.foodreqq', to='food.reqq'),
        ),
        migrations.CreateModel(
            name='buylistmaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.food')),
                ('buylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.reqq')),
            ],
        ),
        migrations.CreateModel(
            name='week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30)])),
                ('month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('year', models.IntegerField(choices=[(1408, 1408), (1409, 1409), (1410, 1410), (1411, 1411), (1412, 1412), (1413, 1413), (1414, 1414), (1415, 1415), (1416, 1416), (1417, 1417), (1418, 1418), (1419, 1419), (1420, 1420), (1421, 1421), (1422, 1422), (1423, 1423), (1424, 1424), (1425, 1425), (1426, 1426), (1427, 1427), (1428, 1428), (1429, 1429), (1430, 1430), (1431, 1431), (1432, 1432), (1433, 1433), (1434, 1434), (1435, 1435), (1436, 1436), (1437, 1437), (1438, 1438), (1439, 1439), (1440, 1440), (1441, 1441), (1442, 1442), (1443, 1443), (1444, 1444), (1445, 1445), (1446, 1446), (1447, 1447), (1448, 1448), (1449, 1449), (1400, 1400), (1401, 1401), (1402, 1402), (1403, 1403), (1404, 1404), (1405, 1405), (1406, 1406), (1407, 1407)])),
                ('type', models.CharField(choices=[('ناهار', 'ناهار'), ('شام', 'شام'), ('صبحانه', 'صبحانه')], max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.food')),
            ],
        ),
    ]
